version: '3'
services:
  postgres:
    image: 'postgres:9.6.1'
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'backend'
    networks: 
      - postgres

  pgAdmin:
    image: sosedoff/pgweb
    restart: on-failure
    networks:
      - internal
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgres://test:test@postgres:5432/backend?sslmode=disable
    depends_on:
      - postgres
    networks: 
      - postgres

networks:
  postgres:
    driver: bridge